language: javascript
node_js:
  - 12
script: npm run build
deploy:
  provider: releases
  token: ahOaa4NqIBy699UlEFXn4xI5qZsTcS0zx47lDQVYyQwM/1jwtBrHOwQHy0Xa3FnT3Wd2QOBH9s+onlUIbfC2N89m3TnxBiyR6ptiXArpUkd+JI1JC0unYR9mPG/hosXiUGVccf53JVhbPALIoEG2J25eHt2YohkqgMu4lWCOCIqT/DfELxR1T1h7I7bjkxS4l7UYU6QpNDx3hjg9dEfs29M0y1wUTNCg5uKA7Y6P1+hywLG0j5RRcHUUT+QTo5g4iVDFJ0ig3w4EJGj3JGtyLldKS0qqOctQY7sCa/Zzu2s+gY+u9iXw1aPJMWPBQ83pxEv5uazHAaPlYP9brurgRQG9XQB1KNbvSNYfNC/2nyj3bvXMoeN1JEN05d2V6w+Z7V87SCfQrgUgnSyO0ThAX2Gl4Nkm2wMAb0uNT452A0YuLtPl2L5tML7nUijNECTsLVLieWyR3uTXuatWXn7BIzFxteJCeu87bvXzm56V6Y7ey6n4L/fZHJkABIHYUXLGXu7XCbUrEhn4jGGZauqOWNMhIvJuYZ3VyGDZSkqFT0nI2eCLCG6iMPh/rh3B3sog7Qz3xj7pkeNMOichk4FJM3V6RQsfLtZBsFdJgQCLVgOOKNKH4YBsFOQFte+I17oKh8Zogu+HZLGMcW9bTXUUjZKNBJmKdMCrccSVwvu7lSM=
  file: './morpher.zip'
  edge: true # opt in to dpl v2
  on:
    tags: true
